[package]
name = "pebblesdk-sys"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

[dependencies]
cty = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }

[package.metadata.docs.rs]
targets = [
  "thumbv7em-none-eabi",
  "thumbv7m-none-eabi",
  "thumbv8m.main-none-eabihf",
]
